### ISSUE TITLE
ClassNotFoundException with PreciousStones

### ISSUE THREAD

**Issue by RoboMWM** [tim-savage/SavageDeathChest#10]
I don't want it nor need it to integrate into PreciousStones though. I've set it to ignore the plugin in the config, but apparently that doesn't stop your plugin from attempting to check anyways.

```
[01:42:48] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to SavageDeathChest v1.6.2
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
	at com.winterhaven_mc.deathchest.ProtectionPlugin$3.hasChestPermission(ProtectionPlugin.java:152) ~[?:?]
	at com.winterhaven_mc.deathchest.ProtectionPlugin.allowChestPlacement(ProtectionPlugin.java:423) ~[?:?]
	at com.winterhaven_mc.deathchest.ChestUtilities.isValidLeftChestLocation(ChestUtilities.java:557) ~[?:?]
	at com.winterhaven_mc.deathchest.ChestUtilities.findValidSingleChestLocation(ChestUtilities.java:273) ~[?:?]
	at com.winterhaven_mc.deathchest.ChestManager.deploySingleChest(ChestManager.java:344) ~[?:?]
	at com.winterhaven_mc.deathchest.ChestManager.deployChest(ChestManager.java:320) ~[?:?]
	at com.winterhaven_mc.deathchest.PlayerEventListener.onPlayerDeath(PlayerEventListener.java:72) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor905.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.2.jar:git-Paper-727]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:409) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityPlayer.die(EntityPlayer.java:421) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:920) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity(EntityHuman.java:783) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityPlayer.damageEntity(EntityPlayer.java:512) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityMonster.B(EntityMonster.java:68) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityZombie.B(EntityZombie.java:236) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PathfinderGoalMeleeAttack.e(SourceFile:122) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PathfinderGoalSelector.a(SourceFile:129) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityInsentient.doTick(EntityInsentient.java:643) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityLiving.n(EntityLiving.java:1935) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityInsentient.n(EntityInsentient.java:482) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityMonster.n(EntityMonster.java:24) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityZombie.n(EntityZombie.java:175) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1795) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:245) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityMonster.m(EntityMonster.java:28) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityZombie.m(EntityZombie.java:232) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1728) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1703) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1528) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:636) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:885) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-727]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: net.sacredlabyrinth.Phaed.PreciousStones.FieldFlag
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.9.2.jar:git-Paper-727]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
	... 41 more

**Comment by tim-savage** [comment]
Thanks for the heads up. It seems that the Precious Stones API has changed since the version I used to build against. I will see if there is a new class or method for performing the permission check, otherwise I will unfortunately have to remove support for Precious Stones.
