### ISSUE TITLE
No Such Method: com.massivecraft.factions.engine.EngineMain.playerCanUseItemHere

### ISSUE THREAD

**Issue by hoorigan** [tim-savage/SavageDeathChest#14]
It looks like this method was moved at some point.  I'm still working on tracking it down, and might be able to submit a fix for it.  Here's the error I'm getting when a player dies in Factions SafeZone:

`[12:20:17 ERROR]: Could not pass event PlayerDeathEvent to SavageDeathChest v1.7.0-beta4
java.lang.NoSuchMethodError: com.massivecraft.factions.engine.EngineMain.playerCanUseItemHere(Lorg/bukkit/entity/Player;Lcom/massivecraft/massivecore/ps/PS;Lorg/bukkit/Material;Z)Z
        at com.winterhaven_mc.deathchest.ProtectionPlugin$1.hasChestPermission(ProtectionPlugin.java:53) ~[?:?]
        at com.winterhaven_mc.deathchest.ProtectionPlugin.allowChestPlacement(ProtectionPlugin.java:467) ~[?:?]
        at com.winterhaven_mc.deathchest.util.LocationUtilities.isValidLeftChestLocation(LocationUtilities.java:443) ~[?:?]
        at com.winterhaven_mc.deathchest.util.LocationUtilities.findValidSingleChestLocation(LocationUtilities.java:163) ~[?:?]
        at com.winterhaven_mc.deathchest.storage.ChestManager.deploySingleChest(ChestManager.java:182) ~[?:?]
        at com.winterhaven_mc.deathchest.storage.ChestManager.deployChest(ChestManager.java:158) ~[?:?]
        at com.winterhaven_mc.deathchest.listeners.PlayerEventListener.onPlayerDeath(PlayerEventListener.java:81) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor765.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1227]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [patched_1.12.2.jar:git-Paper-1227]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:449) [patched_1.12.2.jar:git-Paper-1227]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:972) [patched_1.12.2.jar:git-Paper-1227]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [patched_1.12.2.jar:git-Paper-1227]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:603) [patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:208) [patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:196) [patched_1.12.2.jar:git-Paper-1227]
        at com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:41) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:98) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:26) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:167) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:509) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676) [patched_1.12.2.jar:git-Paper-1227]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:639) [patched_1.12.2.jar:git-Paper-1227]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:464) [patched_1.12.2.jar:git-Paper-1227]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1227]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1227]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1227]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]`

**Comment by tim-savage** [comment]
Factions support has been dropped until a 1.13.x compatible version is released. re-enabling support for factions will be considered then, if the factions api allows.
