### ISSUE TITLE
NPE when loading plugin

### ISSUE THREAD

**Issue by mart-r** [tim-savage/SavageDeathChest#31]
Using the version from spigotmc.org (1.13.0-beta1). I'm not sure which line the actual issue is at because the current source does not fit traceback.
```
[17:14:23] [Server thread/INFO]: [SavageDeathChest] Enabling SavageDeathChest v1.13.0
[17:14:23] [Server thread/INFO]: [SavageDeathChest] Multiverse-Core detected.
[17:14:23] [Server thread/INFO]: [SavageDeathChest] Language file en-US.yml successfully loaded.
[17:14:23] [Server thread/INFO]: [SavageDeathChest] Sound file sounds.yml successfully loaded.
[17:14:23] [Server thread/INFO]: [SavageDeathChest] SQLite datastore initialized.
[17:14:24] [Server thread/ERROR]: Error occurred while enabling SavageDeathChest v1.13.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.winterhaven_mc.deathchest.chests.ChestBlock.destroy(ChestBlock.java:311) ~[?:?]
	at com.winterhaven_mc.deathchest.chests.DeathChest.destroy(DeathChest.java:364) ~[?:?]
	at com.winterhaven_mc.deathchest.chests.DeathChest.expire(DeathChest.java:397) ~[?:?]
	at com.winterhaven_mc.deathchest.chests.ChestManager.loadDeathChests(ChestManager.java:116) ~[?:?]
	at com.winterhaven_mc.deathchest.chests.ChestManager.<init>(ChestManager.java:55) ~[?:?]
	at com.winterhaven_mc.deathchest.PluginMain.onEnable(PluginMain.java:53) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-463]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-463]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-463]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-463]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-463]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-463]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-463]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-463]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-463]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-463]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[17:14:24] [Server thread/INFO]: [SavageDeathChest] Disabling SavageDeathChest v1.13.0
[17:14:24] [Server thread/INFO]: [SavageDeathChest] SQLite datastore connection closed.
```

**Comment by tim-savage** [comment]
This will be fixed in the next version. A method was being called from within a class constructor that referenced the class, which is null until the constructor is completed.
