### ISSUE TITLE
 SavageDeathChest v1.13.0 beta 1 not initialize withowt WorldGuard

### ISSUE THREAD

**Issue by MaoDoBan** [tim-savage/SavageDeathChest#32]
I using SavageDeathChest v1.13.0 beta 1 withowt WorldGuard (i never used WorldGuard before).
I did not see in the bukkit page of SavageDeathChest that WorlGuard was required dependency...

My server running git-Paper-451 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT).

[04:25:35] [Server thread/INFO]: [SavageDeathChest] Enabling SavageDeathChest v1.13.0
[04:25:35] [Server thread/INFO]: [SavageDeathChest] Language file pt-BR.yml successfully loaded.
[04:25:35] [Server thread/INFO]: [SavageDeathChest] Sound file sounds.yml successfully loaded.
[04:25:35] [Server thread/INFO]: [SavageDeathChest] SQLite datastore initialized.
[04:25:35] [Server thread/ERROR]: Error occurred while enabling SavageDeathChest v1.13.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
	at com.winterhaven_mc.deathchest.ProtectionPlugin$4.<init>(ProtectionPlugin.java:221) ~[?:?]
	at com.winterhaven_mc.deathchest.ProtectionPlugin.<clinit>(ProtectionPlugin.java:218) ~[?:?]
	at com.winterhaven_mc.deathchest.PluginMain.onEnable(PluginMain.java:64) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-451]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-451]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-451]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-451]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-451]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-451]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-451]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	... 14 more
[04:25:35] [Server thread/INFO]: [SavageDeathChest] Disabling SavageDeathChest v1.13.0
[04:25:35] [Server thread/INFO]: [SavageDeathChest] SQLite datastore connection closed.

**Comment by tim-savage** [comment]
Thanks for the report, this issue will be fixed in the next version.
