### ISSUE TITLE
Could not pass event PlayerInteractEvent to SavageDeathChest v1.4.5

### ISSUE THREAD

**Issue by bog500** [tim-savage/SavageDeathChest#6]
There is a problem

Stack trace :

[00:38:17] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to SavageDeathChest v1.4.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_60]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_60]
    at java.util.Collections$UnmodifiableList.get(Unknown Source) ~[?:1.8.0_60]
    at com.winterhaven_mc.deathchest.PlayerEventListener.onPlayerInteract(PlayerEventListener.java:125) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    ... 17 more

**Comment by tim-savage** [comment]
likely fixed in current versions. if not, please resubmit a ticket.
